# DataFrames

### Creating a dataframe

In [1]:
import numpy as np 
import pandas as pd

In [16]:
data={
    'Name':['Abhishek','Ansh','Meow','Abhi'],
    'Age':[22,22,18,25],
    'City':['Nagpur','Mumbai','Nagpur','Pune'],
    'Salary':[100000,200000,300000,400000]
}
df=pd.DataFrame(data)

In [5]:
df

       Name  Age    City  Salary
0  Abhishek   22  Nagpur  100000
1      Mini   22  Mumbai  200000
2      Meow   18  Nagpur  300000
3      Abhi   25    Pune  400000

In [5]:
data_list=[
    ['Abhishek',22,'Nagpur',100000],
    ['Ansh',22,'Mumbai',200000],
    ['Meow',18,'Nagpur',300000],
    ['Abhi',25,'Pune',400000]
]
columns=["Name","Age","City","Salary"]
df2=pd.DataFrame(data_list,columns=columns)
df2

       Name  Age    City  Salary
0  Abhishek   22  Nagpur  100000
1      Ansh   22  Mumbai  200000
2      Meow   18  Nagpur  300000
3      Abhi   25    Pune  400000

In [17]:
#Selecting and indexing
df2["Name"]
df2[["Name","Age"]]

       Name  Age
0  Abhishek   22
1      Ansh   22
2      Meow   18
3      Abhi   25

In [6]:
#Creating new colums
df2["Department"]=["IT","HR","Sales","Marketing"]
df2

       Name  Age    City  Salary Department
0  Abhishek   22  Nagpur  100000         IT
1      Ansh   22  Mumbai  200000         HR
2      Meow   18  Nagpur  300000      Sales
3      Abhi   25    Pune  400000  Marketing

In [9]:
#Removing a column
df2.drop("Department",axis=1,inplace=True)

In [10]:
df2

       Name  Age    City  Salary
0  Abhishek   22  Nagpur  100000
1      Ansh   22  Mumbai  200000
2      Meow   18  Nagpur  300000
3      Abhi   25    Pune  400000

In [12]:
#selecting rows
df2.loc[0]
df2.iloc[3]

Name        Abhi
Age           25
City        Pune
Salary    400000
Name: 3, dtype: object

In [14]:
#selecting subset of row and columns
df2.loc[[0,1]][["Name","Age"]]

       Name  Age
0  Abhishek   22
1      Ansh   22

In [15]:
df2.loc[[2,3]][["Name","Salary"]]

   Name  Salary
2  Meow  300000
3  Abhi  400000

In [ ]:
'''condition selection
I only want those people whose age is greater than 20''' 
df2[df2["Age"]>20]

       Name  Age    City  Salary
0  Abhishek   22  Nagpur  100000
1      Ansh   22  Mumbai  200000
3      Abhi   25    Pune  400000

In [25]:
# I only want those people whose age is greater than 20 and from Nagpur
df2[(df2["Age"]>20) & (df2["City"]=="Nagpur")]

       Name  Age    City  Salary
0  Abhishek   22  Nagpur  100000