## Missing Data

In [1]:
import numpy as np 
import pandas as pd

### Finding missing values

In [3]:
data={
    'A': [1, 2, np.nan, 4],     
    'B':[5, np.nan, np.nan, 8],
    'C':[9, 10, 11, 12],
    'D':[np.nan, 14, 15, 16]
}
df=pd.DataFrame(data)

In [4]:
df

     A    B   C     D
0  1.0  5.0   9   NaN
1  2.0  NaN  10  14.0
2  NaN  NaN  11  15.0
3  4.0  8.0  12  16.0

In [6]:
# Check for missing values
df.isna()

       A      B      C      D
0  False  False  False   True
1  False   True  False  False
2   True   True  False  False
3  False  False  False  False

In [7]:
# Count missing values in each column
df.isna().sum()

A    1
B    2
C    0
D    1
dtype: int64

In [8]:
# Check if any missing values exist in each column
df.isna().any()

A     True
B     True
C    False
D     True
dtype: bool

### Removing null values

In [9]:
df

     A    B   C     D
0  1.0  5.0   9   NaN
1  2.0  NaN  10  14.0
2  NaN  NaN  11  15.0
3  4.0  8.0  12  16.0

In [10]:
# Drop rows with missing values
df.dropna()

     A    B   C     D
3  4.0  8.0  12  16.0

In [ ]:
# Drop rows with less than 3 non-NA values
df.dropna(thresh=3)

     A    B   C     D
0  1.0  5.0   9   NaN
1  2.0  NaN  10  14.0
3  4.0  8.0  12  16.0

### Filling the Missing data

In [12]:
df

     A    B   C     D
0  1.0  5.0   9   NaN
1  2.0  NaN  10  14.0
2  NaN  NaN  11  15.0
3  4.0  8.0  12  16.0

In [13]:
  # Fill missing values with 0
df.fillna(value=0)

     A    B   C     D
0  1.0  5.0   9   0.0
1  2.0  0.0  10  14.0
2  0.0  0.0  11  15.0
3  4.0  8.0  12  16.0

In [15]:
# Fill missing values with different values for each column
values={'A':0, 'B':100,'C':200, 'D':400}
df.fillna(value=values)

     A      B   C      D
0  1.0    5.0   9  400.0
1  2.0  100.0  10   14.0
2  0.0  100.0  11   15.0
3  4.0    8.0  12   16.0

In [16]:
df

     A    B   C     D
0  1.0  5.0   9   NaN
1  2.0  NaN  10  14.0
2  NaN  NaN  11  15.0
3  4.0  8.0  12  16.0

In [17]:
# Fill missing values with the mean of each column
df.fillna(df.mean())

          A    B   C     D
0  1.000000  5.0   9  15.0
1  2.000000  6.5  10  14.0
2  2.333333  6.5  11  15.0
3  4.000000  8.0  12  16.0