## Merging joining Concadination

In [1]:
import numpy as np
import pandas as pd

### Merging 2 Dataframes

In [20]:
employee=pd.DataFrame({
    'employee_id': [1, 2, 3,4,5],
    'Name': ['Alice', 'Bob', 'Charlie','David','Eva'],
    'Age': [25, 30, 35,33,24],
    'Department': ['HR', 'IT', 'Finance','HR','IT'],
})

salaries=pd.DataFrame({
    'employee_id': [1, 2, 3,6,7,8],
    'Salary': [50000, 60000, 70000, 80000,90000,100000],
    'bonus': [5000, 6000, 7000, 8000,9000,10000],
})

In [4]:
employee

   employee_id     Name  Age Department
0            1    Alice   25         HR
1            2      Bob   30         IT
2            3  Charlie   35    Finance
3            4    David   40  Marketing

In [8]:
salaries

   employee_id  Salary  bonus
0            1   50000   5000
1            2   60000   6000
2            3   70000   7000
3            4   80000   8000

In [14]:
# Merge the two DataFrames on the 'employee_id' column
pd.merge(employee, salaries, on='employee_id', how='inner')

   employee_id     Name  Age Department  Salary  bonus
0            1    Alice   25         HR   50000   5000
1            2      Bob   30         IT   60000   6000
2            3  Charlie   35    Finance   70000   7000

In [15]:
# Merge the two DataFrames on the 'employee_id' column using a outer join
pd.merge(employee, salaries, on='employee_id', how='outer')

   employee_id     Name   Age Department  Salary  bonus
0            1    Alice  25.0         HR   50000   5000
1            2      Bob  30.0         IT   60000   6000
2            3  Charlie  35.0    Finance   70000   7000
3            4      NaN   NaN        NaN   80000   8000
4            5      NaN   NaN        NaN   90000   9000
5            6      NaN   NaN        NaN  100000  10000

In [21]:
# merge the two DataFrames on the 'employee_id' column using a left join
pd.merge(employee,salaries,on='employee_id', how='left')

   employee_id     Name  Age Department   Salary   bonus
0            1    Alice   25         HR  50000.0  5000.0
1            2      Bob   30         IT  60000.0  6000.0
2            3  Charlie   35    Finance  70000.0  7000.0
3            4    David   33         HR      NaN     NaN
4            5      Eva   24         IT      NaN     NaN

In [22]:
# Merge the two DataFrames on the 'employee_id' column using a right join
pd.merge(employee,salaries,on='employee_id', how='right')

   employee_id     Name   Age Department  Salary  bonus
0            1    Alice  25.0         HR   50000   5000
1            2      Bob  30.0         IT   60000   6000
2            3  Charlie  35.0    Finance   70000   7000
3            6      NaN   NaN        NaN   80000   8000
4            7      NaN   NaN        NaN   90000   9000
5            8      NaN   NaN        NaN  100000  10000

### Concading two DataFrames

In [24]:
df1=pd.DataFrame({
    'A':['A0','A1','A2'],
    'B':['B0','B1','B2'],
    'C':['C0','C1','C2'],
})

df2=pd.DataFrame({
    'A':['A3','A4','A5'],   
    'B':['B3','B4','B5'],
    'C':['C3','C4','C5'],
})

In [25]:
df1

    A   B   C
0  A0  B0  C0
1  A1  B1  C1
2  A2  B2  C2

In [26]:
df2

    A   B   C
0  A3  B3  C3
1  A4  B4  C4
2  A5  B5  C5

In [ ]:
# Concatenate the two DataFrames vertically(colums)
pd.concat([df1,df2])

    A   B   C
0  A0  B0  C0
1  A1  B1  C1
2  A2  B2  C2
0  A3  B3  C3
1  A4  B4  C4
2  A5  B5  C5

In [28]:
# Concatenate the two DataFrames horizontally(rows)
pd.concat([df1,df2],axis=1)

    A   B   C   A   B   C
0  A0  B0  C0  A3  B3  C3
1  A1  B1  C1  A4  B4  C4
2  A2  B2  C2  A5  B5  C5

### Joining two DataFrames

In [5]:
df1=pd.DataFrame({
    'Name':['Alice','Bob','Charlie']
},index=[0,1,3])

df2=pd.DataFrame({
    'Age':[25,30,35]
},index=[0,2,4])

In [32]:
df1

      Name
0    Alice
1      Bob
2  Charlie

In [33]:
df2

   Age
0   25
1   30
2   35

In [6]:
#joining two dataframes using join method
df1.join(df2,how='outer')

      Name   Age
0    Alice  25.0
1      Bob   NaN
2      NaN  30.0
3  Charlie   NaN
4      NaN  35.0

In [7]:
df2.join(df1)

   Age   Name
0   25  Alice
2   30    NaN
4   35    NaN