In [1]:
import numpy as np 
import pandas as pd

In [2]:
import pandas as pd

data = {
    "Name": ["Rahul", "Priya", "Amit", "Sneha", "Rohan"],
    "Age": [21, 22, 20, 23, 21],
    "City": ["Nagpur", "Pune", "Mumbai", "Nagpur", "Pune"],
    "Marks": [85, 92, 78, 88, 95]
}

df = pd.DataFrame(data)

### Display the complete DataFrame.

In [3]:
df

    Name  Age    City  Marks
0  Rahul   21  Nagpur     85
1  Priya   22    Pune     92
2   Amit   20  Mumbai     78
3  Sneha   23  Nagpur     88
4  Rohan   21    Pune     95

### 2. Display the first 3 rows.

In [4]:
df.head(3)  # Display the first 3 rows of the DataFrame

    Name  Age    City  Marks
0  Rahul   21  Nagpur     85
1  Priya   22    Pune     92
2   Amit   20  Mumbai     78

### 3. Display the last 2 rows.

In [5]:
df.tail(2)  # Display the last 2 rows of the DataFrame

    Name  Age    City  Marks
3  Sneha   23  Nagpur     88
4  Rohan   21    Pune     95

### 4. Find the number of rows and columns.

In [7]:
df.shape
print("Number of rows:", df.shape[0])
print("Number of columns:", df.shape[1])

Number of rows: 5
Number of columns: 4

### 5. Display all column names.

In [9]:
df.columns  # Display the column names of the DataFrame

Index(['Name', 'Age', 'City', 'Marks'], dtype='str')

### 6. Find the average marks.

In [11]:
df["Marks"].mean()  # Display the mean of the "Marks" column
print("Average Marks:", df["Marks"].mean())

Average Marks: 87.6